### ISSUE TITLE
Countdown can be fooled

### ISSUE THREAD

**Issue by nighthawk** [leojing/ReusedCellWithNSTimer#2]
I've noticed a bug: When the timer is at X seconds, grab the table view and move it up and down for Y  seconds, then let it go. The timer then continues at X+1 seconds, even though X+Y+1 seconds have passed in real-time!

What do you think causes this problem and how can you fix it?

**Comment by leojing** [comment]
Yep, that's the same reason the I discussed with you in the interview, when run loop mode is UITrackingRunLoopMode(when the tableview scrolls), the main Timer is stopped. I've solve the problem.

**Comment by nighthawk** [comment]
Nice. That indeed fixes the main countdown though the countdowns in the cells still have the same issue, but that can be solved the same way.

**Comment by leojing** [comment]
Oops, the same problem in cell Timer! Finally fixed all the timer problems, cheers~🎈I should check it again to make sure there is no bugs you can find!😏
